import Head from 'next/head'
import { Inter } from 'next/font/google'

import Skills from '@/components/Skills'
import Header from '@/components/Header'
import Contact from '@/components/Contact'
import EducationAndCurses from '@/components/EducationAndCurses'
import Languages from '@/components/Languages'
import ProfessionalExperience from '@/components/ProfessionalExperience'
import HobbiesAndInterest from '@/components/HobbiesAndInterest'

import CareerObjectives from '@/components/CareerObjectives'
import SoftSkill from '../components/SoftSkills'

const inter = Inter({ subsets: ['latin'] })




export default function Home() {
  return (
    <div className='bg-slate-200'>
      <Head>
        <title>CV</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=' bg-slate-200   min-h-screen'>
        <div className='flex items-center justify-around	py-5'>
          <Header />
          <Contact />
        </div>

        <EducationAndCurses />

        <Languages />
        <Skills />
        <SoftSkill />
        <ProfessionalExperience />
        <CareerObjectives />

        <HobbiesAndInterest />


      </div>
    </div>
  )
}
